
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpeaxhzxxkargblurrco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZWF4aHp4eGthcmdibHVycmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzc3NDQsImV4cCI6MjA1ODkxMzc0NH0.P7M5a0gcWLYn94kI6XQrSzqGSFLGbswLhZnp9wVaV7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
